name: CI Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run build (if exists)
        run: npm run build || echo "No build step"

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/ecoreward-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
